/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/pizzaIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class customIcon {
  customIcon._();

  static const _kFontFam = 'pizzaIcon';
  static const String _kFontPkg = null;

  static const IconData pizza = IconData(0xf818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
